export default {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: '', foreground: 'e2e8f0', background: '050a12' },
    { token: 'invalid', foreground: 'ff2d95' },
    { token: 'emphasis', fontstyle: 'italic' },
    { token: 'strong', fontstyle: 'bold' },

    { token: 'variable', foreground: 'e2e8f0' },
    { token: 'variable.predefined', foreground: 'ff6b2b' },
    { token: 'constant', foreground: 'ffb86c' },
    { token: 'comment', foreground: '4a5568', fontstyle: 'italic' },
    { token: 'comment.js', foreground: '4a5568', fontstyle: 'italic' },
    { token: 'comment.css', foreground: '4a5568', fontstyle: 'italic' },
    { token: 'comment.scss', foreground: '4a5568', fontstyle: 'italic' },
    { token: 'number', foreground: 'ff9d45' },
    { token: 'number.hex', foreground: 'ff9d45' },
    { token: 'regexp', foreground: '00ff88' },
    { token: 'annotation', foreground: '00f0ff' },
    { token: 'type', foreground: '0080ff' },

    { token: 'delimiter', foreground: '64748b' },
    { token: 'delimiter.html', foreground: '64748b' },
    { token: 'delimiter.xml', foreground: '64748b' },

    { token: 'tag', foreground: 'ff6b2b' },
    { token: 'tag.id.jade', foreground: 'ff6b2b' },
    { token: 'tag.class.jade', foreground: 'ff6b2b' },
    { token: 'meta.scss', foreground: 'ff6b2b' },
    { token: 'metatag', foreground: '00f0ff' },
    { token: 'metatag.content.html', foreground: '00ff88' },
    { token: 'metatag.html', foreground: '00f0ff' },
    { token: 'metatag.xml', foreground: '00f0ff' },
    { token: 'metatag.php', fontstyle: 'bold' },

    { token: 'key', foreground: '00f0ff' },
    { token: 'string.key.json', foreground: '00f0ff' },
    { token: 'string.value.json', foreground: '00ff88' },

    { token: 'attribute.name', foreground: '00f0ff' },
    { token: 'attribute.value', foreground: '00ff88' },
    { token: 'attribute.value.number', foreground: 'ff9d45' },
    { token: 'attribute.value.unit', foreground: '00ff88' },
    { token: 'attribute.value.html', foreground: 'ffb86c' },
    { token: 'attribute.value.xml', foreground: '00ff88' },

    { token: 'string', foreground: '00ff88' },
    { token: 'string.html', foreground: '00ff88' },
    { token: 'string.sql', foreground: '00ff88' },
    { token: 'string.yaml', foreground: '00ff88' },

    { token: 'keyword', foreground: 'a855f7' },
    { token: 'keyword.json', foreground: 'ff9d45' },
    { token: 'keyword.flow', foreground: 'ff9d45' },
    { token: 'keyword.flow.scss', foreground: 'ff9d45' },

    { token: 'operator.scss', foreground: '64748b' },
    { token: 'operator.sql', foreground: '64748b' },
    { token: 'operator.swift', foreground: '64748b' },
    { token: 'predefined.sql', foreground: 'a855f7' },
  ],
  colors: {
    'editor.background': '#050a12',
    'editor.foreground': '#e2e8f0',
    'editor.lineHighlightBackground': '#0d1320',
    'editor.selectionBackground': '#1e3a5f',
    'editor.inactiveSelectionBackground': '#152238',
    'editorCursor.foreground': '#00f0ff',
    'editorWhitespace.foreground': '#1a2236',
    'editorIndentGuide.background': '#111827',
    'editorIndentGuide.activeBackground': '#1e293b',
    'editorLineNumber.foreground': '#2a3550',
    'editorLineNumber.activeForeground': '#00f0ff',
    'editorGutter.background': '#050a12',
    'editor.selectionHighlightBackground': '#0080ff20',
    'editor.wordHighlightBackground': '#00f0ff15',
    'editor.wordHighlightStrongBackground': '#00f0ff25',
    'editorBracketMatch.background': '#00f0ff15',
    'editorBracketMatch.border': '#00f0ff40',
    'editorOverviewRuler.border': '#111827',
    'scrollbarSlider.background': '#00f0ff15',
    'scrollbarSlider.hoverBackground': '#00f0ff30',
    'scrollbarSlider.activeBackground': '#00f0ff40',
    'editorWidget.background': '#0d1320',
    'editorWidget.border': '#1a2236',
    'editorSuggestWidget.background': '#0d1320',
    'editorSuggestWidget.border': '#1a2236',
    'editorSuggestWidget.selectedBackground': '#1e293b',
    'editorSuggestWidget.highlightForeground': '#00f0ff',
    'editorHoverWidget.background': '#0d1320',
    'editorHoverWidget.border': '#1a2236',
    'peekView.border': '#00f0ff30',
    'peekViewEditor.background': '#0a0f1a',
    'peekViewResult.background': '#0d1320',
    'minimap.background': '#050a12',
  },
};
